### ISSUE TITLE
Docs incomplete

### ISSUE THREAD

**Issue by fabltd** [Joxit/helm-charts#13]
The Helm instructions are incomplete. 

What is the command to actually deploy the UI

**Comment by Joxit** [comment]
Hi,

Are you talking about the documentation located on [my website](https://helm.joxit.dev/charts/docker-registry-ui/) or [GitHub](https://github.com/Joxit/helm-charts/tree/main/charts/docker-registry-ui) or [ArtifactHUB](https://artifacthub.io/packages/helm/joxit/docker-registry-ui) or [the generic README.md](https://github.com/Joxit/helm-charts) ?

**Comment by fabltd** [comment]
It's the generic read me that's missing the install line. Other 2 links are ok.

**Comment by Joxit** [comment]
Okay, thank you for your feedback, the generic README is not supposed to have the installation guide for docker-registry-ui since it should be the main README/lobby for all my charts. I will change that :smile:

**Comment by fabltd** [comment]
Thanks 

What registry do you recommend using along side the UI?

**Comment by Joxit** [comment]
You can use the embed registry server that use the `registry:2.8.2` docker image for a quick setup (you must configure your `dataVolume` or you will lose all your images otherwise)

You can also create your own registry Deployment if you have specific needs such as auth (I may add this feature later).

**Comment by Joxit** [comment]
I've updated the generic README :smile:
